#Recitation 0B: Fundamentals of Numpy & PyTorch

---






## **Contents**

1. Introduction
    1. Setting Up Numpy & Pytorch - install & import
2. Initializations
    1. Numpy Arrays & Tensors
    2. Interconversions
3. Accessing and modifying data
  1. Indexing
  2. Slicing
4. Pivoting Data
  1. Flatten
  1. Squeeze
  1. Reshape
  1. Transpose
5. Combining Data
  1. Cat
  2. Stack
  3. Repeat
  4. Padding
6. Mathematical operations
  1. Point-wise/element-wise operations
  1. Redution operations
  1. Comparison operations
  1. Vector/Matrix operations

## **1. Introduction**

 If you're wondering why it's good to know both libraries, check this out: https://rickwierenga.com/blog/machine%20learning/numpy-vs-pytorch-linalg.html

### 1a. Setting Up Numpy

In [ ]:
#You can set install NumPy by using the following command
!pip install numpy
# If you want to check the version of numpy you are using or if you want to conifrm if it is installed in your system, you can use the following command:
!pip show numpy

Name: numpy
Version: 1.19.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: None
License: BSD
Location: /usr/local/lib/python3.6/dist-packages
Requires: 
Required-by: yellowbrick, xgboost, xarray, wordcloud, umap-learn, torchvision, torchtext, torch, tifffile, thinc, Theano, tensorflow, tensorflow-probability, tensorflow-hub, tensorflow-datasets, tensorboard, tables, statsmodels, spacy, sklearn-pandas, seaborn, scs, scipy, scikit-learn, resampy, qdldl, PyWavelets, python-louvain, pystan, pysndfile, pymc3, pyemd, pyarrow, plotnine, patsy, pandas, osqp, opt-einsum, opencv-python, opencv-contrib-python, numexpr, numba, np-utils, nibabel, moviepy, mlxtend, mizani, missingno, matplotlib, matplotlib-venn, lucid, lightgbm, librosa, knnimpute, Keras, Keras-Preprocessing, kapre, jpeg4py, jaxlib, jax, imgaug, imbalanced-learn, imageio, hyperopt, holoviews, h5py, gym, gensim, folium, fix-ya

In [ ]:
# Run this to ensure that you have properly installed Numpy on your machine and are ready to go!
import numpy as np
np.random.seed(0) #this is to ensure that every time the notebook is run, the same "random" numbers are generated

### 1b. Setting Up Pytorch

In [ ]:
#You can set install Pytorch by using the following command
!pip install torch
# If you want to check the version of pytorch you are using or if you want to conifrm if it is installed in your system, you can use the following command:
!pip show torch

Name: torch
Version: 1.7.0+cu101
Summary: Tensors and Dynamic neural networks in Python with strong GPU acceleration
Home-page: https://pytorch.org/
Author: PyTorch Team
Author-email: packages@pytorch.org
License: BSD-3
Location: /usr/local/lib/python3.6/dist-packages
Requires: dataclasses, typing-extensions, future, numpy
Required-by: torchvision, torchtext, fastai


In [ ]:
# Run this to ensure that you have properly installed Pytorch on your machine and are ready to go!
import torch
torch.manual_seed(0) #this is to ensure that every time the notebook is run, the same "random" numbers are generated

## **2. Initializations**

### 2a. NumPy Arrays



An array is a data structure that stores values of same data type. In Python, this is the main difference between arrays and lists.

In [ ]:
# Initializes a numpy array of zeroes, with size (3,4)
new_array1 = np.zeros((3, 4))
print("First array is:\n", new_array1, "\n")

# Initializes a numpy array of ones, with size (3,4)
new_array2 = np.ones((3, 4))
print("Second array is:\n", new_array2, "\n")

# Initializes a numpy array of zeroes, with size (3,4,5)
new_array3 = np.zeros((3, 4, 5))
print("Third array is:\n", new_array3, "\n")

First array is:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]] 

Second array is:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]] 

Third array is:
 [[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]] 



NumPy arrays can also be initialized with random uniform distribution and integers

In [ ]:
# Initializes a random numpy array with uniformly distributed numbers from the standard normal distribution
new_array4 = np.random.randn(3, 4) 
print("Fourth array is:\n", new_array4, "\n")

# Initializes a random numpy array with randomly distributed integers in the range [0, 3)
new_array5 = np.random.randint(3, size = (4, 5)) 
print("Fifth array is:\n", new_array5, "\n")

Fourth array is:
 [[ 1.76405235  0.40015721  0.97873798  2.2408932 ]
 [ 1.86755799 -0.97727788  0.95008842 -0.15135721]
 [-0.10321885  0.4105985   0.14404357  1.45427351]] 

Fifth array is:
 [[0 1 1 1 1]
 [0 1 0 0 1]
 [2 0 2 0 1]
 [1 2 0 1 1]] 



### 2b. Torch Tensors

A torch.Tensor is a multi-dimensional matrix containing elements of a single data type.

In [ ]:
# Initializes a torch tensor of zeroes, with size (5,3)
new_tensor1 = torch.zeros(size=(5,3))
print("First tensor is:\n", new_tensor1, "\n")

# Initializes a torch tensor of ones, with size (5,3)
new_tensor2 = torch.ones(size=(5,3))
print("Second tensor is:\n", new_tensor2, "\n")

First tensor is:
 tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]) 

Second tensor is:
 tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) 



Tensors can also be initialized in multiple ways

In [ ]:
# Returns a 2-D tensor with ones on the diagonal and zeros elsewhere
new_tensor3 = torch.eye(3)
print("Third tensor is:\n", new_tensor3, "\n")

# Returns a tensor filled with random numbers from a uniform distribution on the interval [0, 1)
new_tensor4 = torch.rand(size=(3,4))
print("Fourth tensor is:\n", new_tensor4, "\n")

# Returns a 1-D tensor with values from the interval [start, end) taken with common difference step beginning from start
new_tensor5 = torch.arange(start=-3, end=9, step=2)
print("Fifth tensor is:\n", new_tensor5, "\n")

Third tensor is:
 tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]]) 

Fourth tensor is:
 tensor([[0.4963, 0.7682, 0.0885, 0.1320],
        [0.3074, 0.6341, 0.4901, 0.8964],
        [0.4556, 0.6323, 0.3489, 0.4017]]) 

Fifth tensor is:
 tensor([-3, -1,  1,  3,  5,  7]) 



### 2c. Interconversions

List --> Numpy Array

In [ ]:
#Converting a list to numpy array

list1 = [1, 2, 3, 4, 5]
print(list1, type(list1), "\n")

list_toarray = np.array(list1)
print(list_toarray, type(list_toarray))

[1, 2, 3, 4, 5] <class 'list'> 

[1 2 3 4 5] <class 'numpy.ndarray'>


List --> Torch Tensor

In [ ]:
#Converting a list to torch tensor

list2 = [6, 7, 8, 9, 10]
print(list2, type(list2), "\n")

list_totensor = torch.tensor(list2)
print(list_totensor, type(list_totensor))

[6, 7, 8, 9, 10] <class 'list'> 

tensor([ 6,  7,  8,  9, 10]) <class 'torch.Tensor'>


Numpy Array --> Torch Tensor

In [ ]:
old_nparray = np.array([1,2,3,4])
print(old_nparray, type(old_nparray), "\n")

# Convert numpy array to tensor 

new_tensor = torch.from_numpy(old_nparray)
print(new_tensor, type(new_tensor), "\n")

[1 2 3 4] <class 'numpy.ndarray'> 

tensor([1, 2, 3, 4]) <class 'torch.Tensor'> 



Torch Tensor --> Numpy Array

In [ ]:
old_tensor = torch.tensor([5,6,7,8])
print(old_tensor, type(old_tensor), "\n")

# Convert tensor to numpy array

new_nparray = old_tensor.detach().numpy()
print(new_nparray, type(new_nparray), "\n")

tensor([5, 6, 7, 8]) <class 'torch.Tensor'> 

[5 6 7 8] <class 'numpy.ndarray'> 



## **3. Accessing & Modifying Data**

**NOTE:** Values can easily be modified by using the accessing method to select the desired section of the array/tensor to be modified


*   Indexing is using the location of an element in an array/tensor to extract it.
*   Slicing is used to obtain/extract a subset of elements in an array/tensor.



In [ ]:
# Original Array
array = np.random.randint(7, size=(3,4,5))
print('Original array:\n', array, '\n')

# Indexing to access individual elements in the array
print('array[0][0][0]\n', array[0][0][0], '\n\n')
print('array[1,2,3]\n', array[1,2,3]), '\n\n'
print('array[-1,-1][-1]\n', array[-1,-1][-1], '\n\n')

# Array Slicing
print("Indexing the array")
print('array[0]\n', array[0], '\n\n') #extracting all elements from first axis at zeroth location
print('array[:1]\n', array[:1], '\n\n') 
print('array[:,1]\n', array[:,1], '\n\n')
print('array[:,:,3]\n', array[:,:,3], '\n\n')
print('array[:,:,-2:]\n', array[:,:,-2:], '\n\n')

Original array:
 [[[1 0 2 4 3]
  [6 3 2 4 2]
  [0 0 4 5 5]
  [6 0 4 1 4]]

 [[1 2 2 0 1]
  [1 1 1 3 6]
  [3 6 2 3 0]
  [6 3 5 4 1]]

 [[2 4 3 4 6]
  [4 4 3 4 4]
  [4 0 6 4 3]
  [2 5 5 5 0]]] 

array[0][0][0]
 1 


array[1,2,3]
 3
array[-1,-1][-1]
 0 


Indexing the array
array[0]
 [[1 0 2 4 3]
 [6 3 2 4 2]
 [0 0 4 5 5]
 [6 0 4 1 4]] 


array[:1]
 [[[1 0 2 4 3]
  [6 3 2 4 2]
  [0 0 4 5 5]
  [6 0 4 1 4]]] 


array[:,1]
 [[6 3 2 4 2]
 [1 1 1 3 6]
 [4 4 3 4 4]] 


array[:,:,3]
 [[4 4 5 1]
 [0 3 3 4]
 [4 4 4 5]] 


array[:,:,-2:]
 [[[4 3]
  [4 2]
  [5 5]
  [1 4]]

 [[0 1]
  [3 6]
  [3 0]
  [4 1]]

 [[4 6]
  [4 4]
  [4 3]
  [5 0]]] 




In [ ]:
# Original Tensor
t = torch.rand(size=(3,4,5))
print('Original Tensor t:', t, '\n')

# Indexing to access individual elements in the tensor
print('t[0][0][0]\n', t[0][0][0])
print('t[1,2,3]\n', t[1,2,3])
print('t[-1,-1][-1]\n', t[-1,-1][-1])
print('\n')

# Tensor Slicing
print("Indexing the tensor")
print('t[0]\n', t[0])
print('t[:1]\n', t[:1])
print('t[:,1]\n', t[:,1])
print('t[:,:,3]\n', t[:,:,3])
print('t[:,:,-2:]\n', t[:,:,-2:])

Original Tensor t: tensor([[[0.0223, 0.1689, 0.2939, 0.5185, 0.6977],
         [0.8000, 0.1610, 0.2823, 0.6816, 0.9152],
         [0.3971, 0.8742, 0.4194, 0.5529, 0.9527],
         [0.0362, 0.1852, 0.3734, 0.3051, 0.9320]],

        [[0.1759, 0.2698, 0.1507, 0.0317, 0.2081],
         [0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
         [0.5846, 0.0332, 0.1387, 0.2422, 0.8155],
         [0.7932, 0.2783, 0.4820, 0.8198, 0.9971]],

        [[0.6984, 0.5675, 0.8352, 0.2056, 0.5932],
         [0.1123, 0.1535, 0.2417, 0.7262, 0.7011],
         [0.2038, 0.6511, 0.7745, 0.4369, 0.5191],
         [0.6159, 0.8102, 0.9801, 0.1147, 0.3168]]]) 

t[0][0][0]
 tensor(0.0223)
t[1,2,3]
 tensor(0.2422)
t[-1,-1][-1]
 tensor(0.3168)


Indexing the tensor
t[0]
 tensor([[0.0223, 0.1689, 0.2939, 0.5185, 0.6977],
        [0.8000, 0.1610, 0.2823, 0.6816, 0.9152],
        [0.3971, 0.8742, 0.4194, 0.5529, 0.9527],
        [0.0362, 0.1852, 0.3734, 0.3051, 0.9320]])
t[:1]
 tensor([[[0.0223, 0.1689, 0.2939, 0.5185, 0.

## **4. Pivoting Data**


In the following section we cover common methods used to pivot and reshape arrays/tensors, namely:
1. Flatten
1. Squeeze
1. Reshape
1. Transpose

**NOTE:**  The size and shape of an array/tensor mean the same thing.

Typically, after we know an array/tensor’s shape, we can deduce a couple of things. First, we can deduce the array/tensor's rank. The rank of an array/tensor is equal to the length of the tensor's shape.

We can also deduce the number of elements contained within the tensor. The number of elements inside an array/tensor is equal to the product of the shape's component values.

The number of elements contained within an array/tensor is important for reshaping because the reshaping must account for the total number of elements present. Reshaping changes the array/tensor's shape but not the underlying data. 

### 4a. Flatten

A flatten operation on an array/tensor reshapes the array/tensor to have a shape that is equal to the number of elements contained in the array/tensor. Flattening an array/tensor means to remove all of the dimensions except for one.

In [ ]:
# Flatten a Numpy Array

original_array = np.random.randint(3, size = (2, 3, 4)) 
print(original_array, "\n", "The dimension of the original array is:", original_array.shape, "\n") 

flattened_array = original_array.flatten()
print(flattened_array, "\n", "The dimension of the flattened array is:", flattened_array.shape, "\n") # Should be 2*3*4

[[[1 1 1 0]
  [1 2 0 1]
  [2 0 2 0]]

 [[1 2 2 1]
  [0 1 1 0]
  [2 2 2 2]]] 
 The dimension of the original array is: (2, 3, 4) 

[1 1 1 0 1 2 0 1 2 0 2 0 1 2 2 1 0 1 1 0 2 2 2 2] 
 The dimension of the flattened array is: (24,) 



In [ ]:
# Flatten a Torch Tensor

original_tensor = torch.rand(size=(2, 3, 4))
print(original_tensor, "\n", "The dimension of the original tensor is:", original_tensor.shape, "\n") 

flattened_tensor = original_tensor.flatten()
print(flattened_tensor, "\n", "The dimension of the flattened tensor is:", flattened_tensor.shape, "\n") # Should be 2*3*4

tensor([[[0.6965, 0.9143, 0.9351, 0.9412],
         [0.5995, 0.0652, 0.5460, 0.1872],
         [0.0340, 0.9442, 0.8802, 0.0012]],

        [[0.5936, 0.4158, 0.4177, 0.2711],
         [0.6923, 0.2038, 0.6833, 0.7529],
         [0.8579, 0.6870, 0.0051, 0.1757]]]) 
 The dimension of the original tensor is: torch.Size([2, 3, 4]) 

tensor([0.6965, 0.9143, 0.9351, 0.9412, 0.5995, 0.0652, 0.5460, 0.1872, 0.0340,
        0.9442, 0.8802, 0.0012, 0.5936, 0.4158, 0.4177, 0.2711, 0.6923, 0.2038,
        0.6833, 0.7529, 0.8579, 0.6870, 0.0051, 0.1757]) 
 The dimension of the flattened tensor is: torch.Size([24]) 



### 4b. Squeeze

The next way we can change the shape of our arrays/tensors is by squeezing and unsqueezing them.

*   Squeezing an array/tensor removes the dimensions or axes that have a length of one.
*   Unsqueezing an array/tensor adds a dimension with a length of one.

These functions allow us to expand or shrink the rank (number of dimensions) of our array/tensor.

In [ ]:
# Original Array
original_array = np.random.randint(3, size = (6, 1, 3))
print("Example of array with single dimension in one of the axis \n", original_array,'\n')

# Squeeze a Numpy Array

squeezed_array = np.squeeze(original_array, axis = 1)
print("The squeezed array is \n",  squeezed_array, "\n and the dimension is", squeezed_array.shape,'\n')

# Unsqueeze a Numpy Array

unsqueezed_array = np.expand_dims(squeezed_array, axis = 1) # can specify which axes by using 'axis = '
print("The unsqueezed array is \n",  unsqueezed_array, "\n and the dimension is", unsqueezed_array.shape)

Example of array with single dimension in one of the axis 
 [[[1 2 2]]

 [[2 2 2]]

 [[0 1 2]]

 [[2 1 2]]

 [[1 0 2]]

 [[2 0 2]]] 

The squeezed array is 
 [[1 2 2]
 [2 2 2]
 [0 1 2]
 [2 1 2]
 [1 0 2]
 [2 0 2]] 
 and the dimension is (6, 3) 

The unsqueezed array is 
 [[[1 2 2]]

 [[2 2 2]]

 [[0 1 2]]

 [[2 1 2]]

 [[1 0 2]]

 [[2 0 2]]] 
 and the dimension is (6, 1, 3)


In [ ]:
# Original Tensor
original_tensor = torch.rand(size=(3, 2, 1, 2))
print("Example of tensor with single dimension in one of the axis \n", original_tensor,'\n')

# Squeeze a Torch Tensor

squeezed_tensor = original_tensor.squeeze(2)
print("The squeezed tensor is \n",  squeezed_tensor, "\n and the dimension is", squeezed_tensor.shape,'\n')

# Unsqueeze a Torch Tensor

unsqueezed_tensor = squeezed_tensor.unsqueeze(2) 
print("The unsqueezed tensor is \n",  unsqueezed_tensor, "\n and the dimension is", unsqueezed_tensor.shape)

Example of tensor with single dimension in one of the axis 
 tensor([[[[0.7497, 0.6047]],

         [[0.1100, 0.2121]]],


        [[[0.9704, 0.8369]],

         [[0.2820, 0.3742]]],


        [[[0.0237, 0.4910]],

         [[0.1235, 0.1143]]]]) 

The squeezed tensor is 
 tensor([[[0.7497, 0.6047],
         [0.1100, 0.2121]],

        [[0.9704, 0.8369],
         [0.2820, 0.3742]],

        [[0.0237, 0.4910],
         [0.1235, 0.1143]]]) 
 and the dimension is torch.Size([3, 2, 2]) 

The unsqueezed tensor is 
 tensor([[[[0.7497, 0.6047]],

         [[0.1100, 0.2121]]],


        [[[0.9704, 0.8369]],

         [[0.2820, 0.3742]]],


        [[[0.0237, 0.4910]],

         [[0.1235, 0.1143]]]]) 
 and the dimension is torch.Size([3, 2, 1, 2])


### 4c. Reshape

Using the reshape() function, we can specify the shape that we are seeking. Notice how all of the shapes have to account for the number of elements in the tensor.

In [ ]:
# Reshaping a Numpy Array

original_array = np.random.randint(3, size = (2, 3, 4)) 
print(original_array, "\n", "The dimension of the original array is:", original_array.shape, "\n") 

reshaped_array1 = np.reshape(original_array, (4, 2, 3))
print(reshaped_array1, "\n", "The dimension of the reshaped array is:", reshaped_array1.shape, "\n") # Product of size should be same as orginal

reshaped_array2 = np.reshape(original_array, (6, 4))
print(reshaped_array2, "\n", "The dimension of the reshaped array is:", reshaped_array2.shape, "\n") # Product of size should be same as orginal


[[[0 0 2 0]
  [2 2 2 0]
  [0 0 1 2]]

 [[0 1 2 2]
  [2 1 0 0]
  [0 0 2 2]]] 
 The dimension of the original array is: (2, 3, 4) 

[[[0 0 2]
  [0 2 2]]

 [[2 0 0]
  [0 1 2]]

 [[0 1 2]
  [2 2 1]]

 [[0 0 0]
  [0 2 2]]] 
 The dimension of the reshaped array is: (4, 2, 3) 

[[0 0 2 0]
 [2 2 2 0]
 [0 0 1 2]
 [0 1 2 2]
 [2 1 0 0]
 [0 0 2 2]] 
 The dimension of the reshaped array is: (6, 4) 



In [ ]:
# Reshaping a Torch Tensor

original_tensor = torch.rand(size=(3, 1, 2, 2))
print(original_tensor, "\n", "The dimension of the original tensor is:", original_tensor.shape, "\n") 

reshaped_tensor1 = original_tensor.reshape(3, 4, 1)
print(reshaped_tensor1, "\n", "The dimension of the reshaped tensor is:", reshaped_tensor1.shape, "\n") # Product of size should be same as orginal

reshaped_tensor2 = original_tensor.reshape(2, 6)
print(reshaped_tensor2, "\n", "The dimension of the reshaped tensor is:", reshaped_tensor2.shape, "\n") # Product of size should be same as orginal


tensor([[[[0.4725, 0.5751],
          [0.2952, 0.7967]]],


        [[[0.1957, 0.9537],
          [0.8426, 0.0784]]],


        [[[0.3756, 0.5226],
          [0.5730, 0.6186]]]]) 
 The dimension of the original tensor is: torch.Size([3, 1, 2, 2]) 

tensor([[[0.4725],
         [0.5751],
         [0.2952],
         [0.7967]],

        [[0.1957],
         [0.9537],
         [0.8426],
         [0.0784]],

        [[0.3756],
         [0.5226],
         [0.5730],
         [0.6186]]]) 
 The dimension of the reshaped tensor is: torch.Size([3, 4, 1]) 

tensor([[0.4725, 0.5751, 0.2952, 0.7967, 0.1957, 0.9537],
        [0.8426, 0.0784, 0.3756, 0.5226, 0.5730, 0.6186]]) 
 The dimension of the reshaped tensor is: torch.Size([2, 6]) 



**Special Case:** Numpy/Pytorch allow us to give one of new shape parameter as -1 (eg: (2,-1) or (-1,3) but not (-1, -1)). It simply means that it is an unknown dimension and we want numpy/pytorch to figure it out. Numpy/Pytorch will figure this by looking at the 'length of the array and remaining dimensions' and making sure it satisfies the above mentioned criteria

In [ ]:
# Reshaping a Numpy Array with -1

original_array = np.random.randint(3, size = (2, 3, 4)) 
print(original_array, "\n", "The dimension of the original array is:", original_array.shape, "\n") 

reshaped_array1 = np.reshape(original_array, (4, -1, 3)) # Numpy will automatically infer that the missing size is 2
print(reshaped_array1, "\n", "The dimension of the reshaped array is:", reshaped_array1.shape, "\n") # Product of size should be same as orginal

reshaped_array2 = np.reshape(original_array, (-1)) # Numpy will automatically infer that the missing size is 24
print(reshaped_array2, "\n", "The dimension of the reshaped array is:", reshaped_array2.shape, "\n") # Product of size should be same as orginal


[[[0 0 0 1]
  [2 0 0 1]
  [0 2 1 1]]

 [[1 0 0 0]
  [1 1 2 1]
  [0 0 1 2]]] 
 The dimension of the original array is: (2, 3, 4) 

[[[0 0 0]
  [1 2 0]]

 [[0 1 0]
  [2 1 1]]

 [[1 0 0]
  [0 1 1]]

 [[2 1 0]
  [0 1 2]]] 
 The dimension of the reshaped array is: (4, 2, 3) 

[0 0 0 1 2 0 0 1 0 2 1 1 1 0 0 0 1 1 2 1 0 0 1 2] 
 The dimension of the reshaped array is: (24,) 



In [ ]:
# Reshaping a Torch Tensor with -1

original_tensor = torch.rand(size=(3, 2, 1, 2))
print(original_tensor, "\n", "The dimension of the original tensor is:", original_tensor.shape, "\n") 

reshaped_tensor1 = original_tensor.reshape(3, -1, 1) # Torch will automatically infer that the missing size is 4
print(reshaped_tensor1, "\n", "The dimension of the reshaped tensor is:", reshaped_tensor1.shape, "\n") # Product of size should be same as orginal

reshaped_tensor2 = original_tensor.reshape(-1) # Torch will automatically infer that the missing size is 12
print(reshaped_tensor2, "\n", "The dimension of the reshaped tensor is:", reshaped_tensor2.shape, "\n") # Product of size should be same as orginal


tensor([[[[0.6962, 0.5300]],

         [[0.2560, 0.7366]]],


        [[[0.0204, 0.2036]],

         [[0.3748, 0.2564]]],


        [[[0.3251, 0.0902]],

         [[0.3936, 0.6069]]]]) 
 The dimension of the original tensor is: torch.Size([3, 2, 1, 2]) 

tensor([[[0.6962],
         [0.5300],
         [0.2560],
         [0.7366]],

        [[0.0204],
         [0.2036],
         [0.3748],
         [0.2564]],

        [[0.3251],
         [0.0902],
         [0.3936],
         [0.6069]]]) 
 The dimension of the reshaped tensor is: torch.Size([3, 4, 1]) 

tensor([0.6962, 0.5300, 0.2560, 0.7366, 0.0204, 0.2036, 0.3748, 0.2564, 0.3251,
        0.0902, 0.3936, 0.6069]) 
 The dimension of the reshaped tensor is: torch.Size([12]) 



**HINT!!** Reshape(-1) essentially does the same things as Flatten()

### 4d. Transpose

**NUMPY:** If the axes are specified, it must be a tuple or list which contains a permutation of [0,1,..,N-1] where N is the number of axes of the array. The i’th axis of the returned array will correspond to the axis numbered axes[i] of the input. If not specified, defaults to range(a.ndim)[::-1], which reverses the order of the axes.

In [ ]:
# Transposing a Numpy Array

original_array = np.random.randint(3, size = (2, 3)) 
print(original_array, "\n", "The dimension of the original array is:", original_array.shape, "\n") 

transposed_array1 = np.transpose(original_array) # If left empty, prefrom matrix transposition
print(transposed_array1, "\n", "The dimension of the transposed array is:", transposed_array1.shape, "\n")

[[1 1 1]
 [0 0 0]] 
 The dimension of the original array is: (2, 3) 

[[1 0]
 [1 0]
 [1 0]] 
 The dimension of the transposed array is: (3, 2) 



In [ ]:
example_array = np.array([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
print(example_array, "\n", "The dimension of this example array is:", example_array.shape, "\n") 

transposed_exampleX = np.transpose(example_array, axes = (0,1,2)) # axes tuple must be of size n-1 where n = rank of array (3 in this case)
print(transposed_exampleX, "\n", "The dimension of the transposed array (0,1,2) is:", transposed_exampleX.shape, "\n") # nothing has changed here

transposed_example1 = np.transpose(example_array, axes = (1,0,2)) 
print(transposed_example1, "\n", "The dimension of the transposed array (1,0,2) is:", transposed_example1.shape, "\n")

transposed_example2 = np.transpose(example_array, axes = (2,1,0))
print(transposed_example2, "\n", "The dimension of the transposed array (2,1,0) is:", transposed_example2.shape, "\n")

transposed_example3 = np.transpose(example_array, axes = (1,0,2))
print(transposed_example3, "\n", "The dimension of the transposed array (1,0,2) is:", transposed_example3.shape, "\n")

transposed_example4 = np.transpose(example_array, axes = (1,2,0)) 
print(transposed_example4, "\n", "The dimension of the transposed array (1,2,0) is:", transposed_example4.shape, "\n")

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ -1  -2  -3  -4]
  [ -5  -6  -7  -8]
  [ -9 -10 -11 -12]]] 
 The dimension of this example array is: (2, 3, 4) 

[[[  1   2   3   4]
  [  5   6   7   8]
  [  9  10  11  12]]

 [[ -1  -2  -3  -4]
  [ -5  -6  -7  -8]
  [ -9 -10 -11 -12]]] 
 The dimension of the transposed array (0,1,2) is: (2, 3, 4) 

[[[  1   2   3   4]
  [ -1  -2  -3  -4]]

 [[  5   6   7   8]
  [ -5  -6  -7  -8]]

 [[  9  10  11  12]
  [ -9 -10 -11 -12]]] 
 The dimension of the transposed array (1,0,2) is: (3, 2, 4) 

[[[  1  -1]
  [  5  -5]
  [  9  -9]]

 [[  2  -2]
  [  6  -6]
  [ 10 -10]]

 [[  3  -3]
  [  7  -7]
  [ 11 -11]]

 [[  4  -4]
  [  8  -8]
  [ 12 -12]]] 
 The dimension of the transposed array (2,1,0) is: (4, 3, 2) 

[[[  1   2   3   4]
  [ -1  -2  -3  -4]]

 [[  5   6   7   8]
  [ -5  -6  -7  -8]]

 [[  9  10  11  12]
  [ -9 -10 -11 -12]]] 
 The dimension of the transposed array (1,0,2) is: (3, 2, 4) 

[[[  1  -1]
  [  2  -2]
  [  3  -3]
  

**PYTORCH:** Returns a tensor that is a transposed version of input. The given dimensions are swapped. The resulting tensor shares it’s underlying storage with the input tensor, so changing the content of one would change the content of the other.

In [ ]:
# Transposing a Torch Tensor

original_tensor = torch.rand(size=(2, 3))
print(original_tensor, "\n", "The dimension of the original tensor is:", original_tensor.shape, "\n") 

transposed_tensor1 = original_tensor.transpose(0,1) # Cannot be left empty - would also be the same as original_tensor.transpose(1, 0)
print(transposed_tensor1, "\n", "The dimension of the transposed tensor is:", transposed_tensor1.shape, "\n")


tensor([[0.1743, 0.4743, 0.8579],
        [0.4486, 0.5139, 0.4569]]) 
 The dimension of the original tensor is: torch.Size([2, 3]) 

tensor([[0.1743, 0.4486],
        [0.4743, 0.5139],
        [0.8579, 0.4569]]) 
 The dimension of the transposed tensor is: torch.Size([3, 2]) 



In [ ]:
example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
print(example_tensor, "\n", "The dimension of this example tensor is:", example_tensor.shape, "\n") 

example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
transposed_example1 = example_tensor.transpose(0,1)
print(transposed_example1, "\n", "The dimension of the transposed tensor (0,1,2) is:", transposed_example1.shape, "\n")

example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
transposed_example2 = example_tensor.transpose(0,2)
print(transposed_example2, "\n", "The dimension of the transposed tensor (1,0,2) is:", transposed_example2.shape, "\n")

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]]) 
 The dimension of this example tensor is: torch.Size([2, 3, 4]) 

tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]]) 
 The dimension of the transposed tensor (0,1,2) is: torch.Size([3, 2, 4]) 

tensor([[[  1,  -1],
         [  5,  -5],
         [  9,  -9]],

        [[  2,  -2],
         [  6,  -6],
         [ 10, -10]],

        [[  3,  -3],
         [  7,  -7],
         [ 11, -11]],

        [[  4,  -4],
         [  8,  -8],
         [ 12, -12]]]) 
 The dimension of the transposed tensor (1,0,2) is: torch.Size([4, 3, 2]) 



**NOTE:** For Torch, the *permute* operation operation allows the user to simultaneously reorder multiple dimensions unlike *transpose* which interchanges two dimensions only. 

PyTorch torch.permute() rearranges the original tensor according to the desired ordering and returns a new multidimensional rotated tensor. The size of the returned tensor remains the same as that of the original.

In [ ]:
example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
transposed_exampleX = example_tensor.permute(0,1,2)
print(transposed_exampleX, "\n", "The dimension of the transposed tensor (0,1,2) is:", transposed_exampleX.shape, "\n") # nothing has changed here

example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
transposed_example3 = example_tensor.permute(1,0,2)
print(transposed_example3, "\n", "The dimension of the transposed tensor (1,0,2) is:", transposed_example3.shape, "\n")

example_tensor = torch.tensor([[[1,2,3,4],[5,6,7,8],[9,10,11,12]],[[-1,-2,-3,-4],[-5,-6,-7,-8],[-9,-10,-11,-12]]])
transposed_example4 = example_tensor.permute(1,2,0)
print(transposed_example4, "\n", "The dimension of the transposed tensor (1,2,0) is:", transposed_example4.shape, "\n")

tensor([[[  1,   2,   3,   4],
         [  5,   6,   7,   8],
         [  9,  10,  11,  12]],

        [[ -1,  -2,  -3,  -4],
         [ -5,  -6,  -7,  -8],
         [ -9, -10, -11, -12]]]) 
 The dimension of the transposed tensor (0,1,2) is: torch.Size([2, 3, 4]) 

tensor([[[  1,   2,   3,   4],
         [ -1,  -2,  -3,  -4]],

        [[  5,   6,   7,   8],
         [ -5,  -6,  -7,  -8]],

        [[  9,  10,  11,  12],
         [ -9, -10, -11, -12]]]) 
 The dimension of the transposed tensor (1,0,2) is: torch.Size([3, 2, 4]) 

tensor([[[  1,  -1],
         [  2,  -2],
         [  3,  -3],
         [  4,  -4]],

        [[  5,  -5],
         [  6,  -6],
         [  7,  -7],
         [  8,  -8]],

        [[  9,  -9],
         [ 10, -10],
         [ 11, -11],
         [ 12, -12]]]) 
 The dimension of the transposed tensor (1,2,0) is: torch.Size([3, 4, 2]) 



## **5. Combining Data**

In the following section we cover common methods used to combine data in arrays/tensors, namely:
1. Concatenation
2. Stack
3. Repeat
4. Padding

### 5a. Concatenation

A concatenation operation joins a sequence of arrays/tensors along an *existing* axis. All arrays/tensors must either have the same shape (except in the concatenating dimension) or be empty.

In [ ]:
# Concatenating Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

concatenated_array1 = np.concatenate((array1, array2), axis = 0) 
print("Concatenated array 1 is \n", concatenated_array1, "\n\n", "and the dimensions of the concatenated array 1 are: \n", concatenated_array1.shape)

concatenated_array2 = np.concatenate((array1, array2), axis = 1) 
print("Concatenated array 2 is \n", concatenated_array2, "\n\n", "and the dimensions of the concatenated array 2 are: \n", concatenated_array2.shape)

concatenated_array3 = np.concatenate((array1, array2), axis = 2) 
print("Concatenated array 3 is \n", concatenated_array3, "\n\n", "and the dimensions of the concatenated array 3 are: \n", concatenated_array3.shape)


Array 1 is 
 [[[1 2 1 1 0]
  [0 1 2 0 2]
  [2 1 1 1 2]
  [0 0 1 0 2]]

 [[2 0 2 2 2]
  [1 1 0 0 0]
  [2 2 1 1 0]
  [0 2 1 1 2]]

 [[0 1 1 1 1]
  [1 2 2 2 0]
  [1 2 1 1 1]
  [1 0 2 2 0]]]  with dimensions  (3, 4, 5) 

Array 2 is 
 [[[1 1 0 3 0]
  [0 3 2 1 2]
  [1 2 0 2 0]
  [1 1 1 0 3]]

 [[0 3 0 0 0]
  [0 1 3 3 0]
  [3 2 2 1 1]
  [1 2 1 1 0]]

 [[1 2 1 1 0]
  [0 1 1 2 3]
  [3 1 3 3 3]
  [2 2 1 2 3]]]  with dimensions  (3, 4, 5) 

Concatenated array 1 is 
 [[[1 2 1 1 0]
  [0 1 2 0 2]
  [2 1 1 1 2]
  [0 0 1 0 2]]

 [[2 0 2 2 2]
  [1 1 0 0 0]
  [2 2 1 1 0]
  [0 2 1 1 2]]

 [[0 1 1 1 1]
  [1 2 2 2 0]
  [1 2 1 1 1]
  [1 0 2 2 0]]

 [[1 1 0 3 0]
  [0 3 2 1 2]
  [1 2 0 2 0]
  [1 1 1 0 3]]

 [[0 3 0 0 0]
  [0 1 3 3 0]
  [3 2 2 1 1]
  [1 2 1 1 0]]

 [[1 2 1 1 0]
  [0 1 1 2 3]
  [3 1 3 3 3]
  [2 2 1 2 3]]] 

 and the dimensions of the concatenated array 1 are: 
 (6, 4, 5)
Concatenated array 2 is 
 [[[1 2 1 1 0]
  [0 1 2 0 2]
  [2 1 1 1 2]
  [0 0 1 0 2]
  [1 1 0 3 0]
  [0 3 2 1 2]
  [1 2 0 2 0]
 

In [ ]:
# Concatenating Torch Tensors

tensor1 = torch.rand(size=(3, 4, 5))
print("Tensor 1 is \n", tensor1, " with dimensions ", tensor1.shape, "\n")

tensor2 = torch.rand(size=(3, 4, 5))
print("Tensor 2 is \n", tensor2, " with dimensions ", tensor2.shape, "\n")

concatenated_tensor1 = torch.cat([tensor1, tensor2],dim=0)
print("Concatenated tensor 1 is \n", concatenated_tensor1, "\n\n", "and the dimensions of the concatenated tensor 1 are: \n", concatenated_tensor1.shape)

concatenated_tensor2 = torch.cat([tensor1, tensor2],dim=1)
print("Concatenated tensor 2 is \n", concatenated_tensor2, "\n\n", "and the dimensions of the concatenated tensor 2 are: \n", concatenated_tensor2.shape)

concatenated_tensor3 = torch.cat([tensor1, tensor2],dim=2)
print("Concatenated tensor 3 is \n", concatenated_tensor3, "\n\n", "and the dimensions of the concatenated tensor 3 are: \n", concatenated_tensor3.shape)


Tensor 1 is 
 tensor([[[0.6012, 0.8179, 0.9736, 0.8175, 0.9747],
         [0.4638, 0.0508, 0.2630, 0.8405, 0.4968],
         [0.2515, 0.1168, 0.0321, 0.0780, 0.3986],
         [0.7742, 0.7703, 0.0178, 0.8119, 0.1087]],

        [[0.3943, 0.2973, 0.4037, 0.4018, 0.0513],
         [0.0683, 0.4218, 0.5065, 0.2729, 0.6883],
         [0.0500, 0.4663, 0.9397, 0.2961, 0.9515],
         [0.6811, 0.0488, 0.8163, 0.4423, 0.2768]],

        [[0.8998, 0.0960, 0.5537, 0.3953, 0.8571],
         [0.6396, 0.7403, 0.6766, 0.3798, 0.3948],
         [0.0880, 0.7709, 0.8970, 0.8421, 0.1473],
         [0.5223, 0.1475, 0.2248, 0.2086, 0.6709]]])  with dimensions  torch.Size([3, 4, 5]) 

Tensor 2 is 
 tensor([[[0.2020, 0.4891, 0.5210, 0.8223, 0.1220],
         [0.1567, 0.2097, 0.8500, 0.3203, 0.9217],
         [0.6808, 0.5633, 0.4963, 0.4012, 0.5627],
         [0.3858, 0.4965, 0.5638, 0.1089, 0.2379]],

        [[0.9037, 0.0942, 0.4641, 0.9946, 0.6806],
         [0.5142, 0.0667, 0.7477, 0.1439, 0.3581],
    

### 5b. Stacking

The stack operation joins a sequence of arrays/tensors along a *new* axis. The axis parameter specifies the index of the new axis in the dimensions of the result. For example, if axis=0 it will be the first dimension and if axis=-1 it will be the last dimension. All arrays/tensors need to be of the same size.  The stacked array/tensor has one more dimension than the input arrays.

In [ ]:
# Stacking Numpy Arrays

array1 = np.random.randint(3, size = (3, 4, 5))
print("Array 1 is \n", array1, " with dimensions ", array1.shape, "\n")

array2 = np.random.randint(4, size = (3, 4, 5))
print("Array 2 is \n", array2, " with dimensions ", array2.shape, "\n")

stacked_array1 = np.stack((array1, array2), axis = 0) 
print("Stacked array 1 is \n", stacked_array1, "\n\n", "and the dimensions of the stacked array 1 are: \n", stacked_array1.shape)

stacked_array2 = np.stack((array1, array2), axis = 1) 
print("Stacked array 2 is \n", stacked_array2, "\n\n", "and the dimensions of the stacked array 2 are: \n", stacked_array2.shape)

stacked_array3 = np.stack((array1, array2), axis = 2) 
print("Stacked array 3 is \n", stacked_array3, "\n\n", "and the dimensions of the stacked array 3 are: \n", stacked_array3.shape)

stacked_array4 = np.stack((array1, array2), axis = -1)
print("Stacked array 4 is \n", stacked_array4, "\n\n", "and the dimensions of the stacked array 4 are: \n", stacked_array4.shape)


Array 1 is 
 [[[2 0 1 1 1]
  [2 1 1 1 2]
  [0 1 0 1 1]
  [2 0 2 0 2]]

 [[0 2 0 0 0]
  [0 1 2 0 0]
  [1 2 1 0 0]
  [0 0 0 1 0]]

 [[2 2 2 0 0]
  [2 0 2 2 0]
  [1 1 1 0 0]
  [1 0 0 1 2]]]  with dimensions  (3, 4, 5) 

Array 2 is 
 [[[2 0 2 1 3]
  [3 3 1 2 1]
  [2 3 2 1 2]
  [3 3 0 0 2]]

 [[1 3 1 2 2]
  [1 0 2 3 0]
  [2 0 3 2 1]
  [2 1 0 1 1]]

 [[2 2 3 0 1]
  [0 3 0 0 2]
  [0 3 1 0 3]
  [2 1 3 0 1]]]  with dimensions  (3, 4, 5) 

Stacked array 1 is 
 [[[[2 0 1 1 1]
   [2 1 1 1 2]
   [0 1 0 1 1]
   [2 0 2 0 2]]

  [[0 2 0 0 0]
   [0 1 2 0 0]
   [1 2 1 0 0]
   [0 0 0 1 0]]

  [[2 2 2 0 0]
   [2 0 2 2 0]
   [1 1 1 0 0]
   [1 0 0 1 2]]]


 [[[2 0 2 1 3]
   [3 3 1 2 1]
   [2 3 2 1 2]
   [3 3 0 0 2]]

  [[1 3 1 2 2]
   [1 0 2 3 0]
   [2 0 3 2 1]
   [2 1 0 1 1]]

  [[2 2 3 0 1]
   [0 3 0 0 2]
   [0 3 1 0 3]
   [2 1 3 0 1]]]] 

 and the dimensions of the stacked array 1 are: 
 (2, 3, 4, 5)
Stacked array 2 is 
 [[[[2 0 1 1 1]
   [2 1 1 1 2]
   [0 1 0 1 1]
   [2 0 2 0 2]]

  [[2 0 2 1 3]
   [3 3

In [ ]:
# Stacking Torch Tensors

tensor1 = torch.rand(size=(3, 4, 5))
print("Tensor 1 is \n", tensor1, " with dimensions ", tensor1.shape, "\n")

tensor2 = torch.rand(size=(3, 4, 5))
print("Tensor 2 is \n", tensor2, " with dimensions ", tensor2.shape, "\n")

stacked_tensor1 = torch.stack([tensor1, tensor2],dim=0)
print("Stacked tensor 1 is \n", stacked_tensor1, "\n\n", "and the dimensions of the stacked tensor 1 are: \n", stacked_tensor1.shape)

stacked_tensor2 = torch.stack([tensor1, tensor2],dim=1)
print("Stacked tensor 2 is \n", stacked_tensor2, "\n\n", "and the dimensions of the stacked tensor 2 are: \n", stacked_tensor2.shape)

stacked_tensor3 = torch.stack([tensor1, tensor2],dim=2)
print("Stacked tensor 3 is \n", stacked_tensor3, "\n\n", "and the dimensions of the stacked tensor 3 are: \n", stacked_tensor3.shape)

stacked_tensor4 = torch.stack([tensor1, tensor2],dim=-1)
print("Stacked tensor 4 is \n", stacked_tensor4, "\n\n", "and the dimensions of the stacked tensor 4 are: \n", stacked_tensor4.shape)

Tensor 1 is 
 tensor([[[0.2599, 0.1663, 0.2119, 0.7875, 0.7648],
         [0.8838, 0.6814, 0.3330, 0.3603, 0.6477],
         [0.9110, 0.6359, 0.2634, 0.2650, 0.0273],
         [0.6080, 0.2194, 0.0542, 0.9384, 0.1753]],

        [[0.4431, 0.6432, 0.5159, 0.1636, 0.0958],
         [0.8985, 0.5814, 0.9148, 0.3324, 0.6473],
         [0.3857, 0.4778, 0.1955, 0.6691, 0.6581],
         [0.4897, 0.3875, 0.1918, 0.8458, 0.1278]],

        [[0.7048, 0.3319, 0.2588, 0.5898, 0.2403],
         [0.6152, 0.5982, 0.1288, 0.5832, 0.7130],
         [0.6979, 0.4371, 0.0901, 0.4229, 0.6737],
         [0.3176, 0.6898, 0.8330, 0.2389, 0.5049]]])  with dimensions  torch.Size([3, 4, 5]) 

Tensor 2 is 
 tensor([[[0.7067, 0.5392, 0.5418, 0.5624, 0.1069],
         [0.5393, 0.8462, 0.9506, 0.7939, 0.5670],
         [0.7335, 0.2568, 0.0857, 0.0700, 0.9988],
         [0.8174, 0.1544, 0.6956, 0.8776, 0.9998]],

        [[0.9372, 0.8874, 0.3854, 0.3245, 0.9105],
         [0.7802, 0.1991, 0.9495, 0.7416, 0.7726],
    

### 5c. Repeat

The repeat operation repeats elements of an array. The number of repetitions for each element is broadcasted to fit the shape of the given axis.

In [ ]:
# Repeat in Numpy Arrays

original_array = np.array([[1,2],[3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

repeated_array1 = np.repeat(original_array, 2)
print("Repeated array 1 is \n", repeated_array1, "\n\n", "and the dimensions of the repeated array 1 are: \n", repeated_array1.shape)

repeated_array2 = np.repeat(original_array, 3, axis=0)
print("Repeated array 2 is \n", repeated_array2, "\n\n", "and the dimensions of the repeated array 2 are: \n", repeated_array2.shape)

repeated_array3 = np.repeat(original_array, 3, axis=1)
print("Repeated array 3 is \n", repeated_array3, "\n\n", "and the dimensions of the repeated array 3 are: \n", repeated_array3.shape)

repeated_array4 = np.repeat(original_array, [2,3], axis=0)
print("Repeated array 4 is \n", repeated_array4, "\n\n", "and the dimensions of the repeated array 4 are: \n", repeated_array4.shape)


Array is 
 [[1 2]
 [3 4]]  with dimensions  (2, 2) 

Repeated array 1 is 
 [1 1 2 2 3 3 4 4] 

 and the dimensions of the repeated array 1 are: 
 (8,)
Repeated array 2 is 
 [[1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 2 are: 
 (6, 2)
Repeated array 3 is 
 [[1 1 1 2 2 2]
 [3 3 3 4 4 4]] 

 and the dimensions of the repeated array 3 are: 
 (2, 6)
Repeated array 4 is 
 [[1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 

 and the dimensions of the repeated array 4 are: 
 (5, 2)


**NOTE:** In the Torch version of 'repeat', only the number of repeats can be specified, and will be done along each dimension. This can, however, be done using 'repeat_interleave'.

In [ ]:
# Repeat in Torch Tensors

original_tensor = torch.tensor([1,2,3,4])
print("Tensor is \n", original_tensor, " with dimensions ", original_tensor.shape, "\n")

repeated_tensor1 = original_tensor.repeat((0))
print("Repeated tensor 1 is \n", repeated_tensor1, "\n\n", "and the dimensions of the repeated tensor 1 are: \n", repeated_tensor1.shape)

repeated_tensor2 = original_tensor.repeat((2))
print("Repeated tensor 2 is \n", repeated_tensor2, "\n\n", "and the dimensions of the repeated tensor 2 are: \n", repeated_tensor2.shape)

repeated_tensor3 = original_tensor.repeat((2,3))
print("Repeated tensor 3 is \n", repeated_tensor3, "\n\n", "and the dimensions of the repeated tensor 3 are: \n", repeated_tensor3.shape)

Tensor is 
 tensor([1, 2, 3, 4])  with dimensions  torch.Size([4]) 

Repeated tensor 1 is 
 tensor([], dtype=torch.int64) 

 and the dimensions of the repeated tensor 1 are: 
 torch.Size([0])
Repeated tensor 2 is 
 tensor([1, 2, 3, 4, 1, 2, 3, 4]) 

 and the dimensions of the repeated tensor 2 are: 
 torch.Size([8])
Repeated tensor 3 is 
 tensor([[1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4],
        [1, 2, 3, 4, 1, 2, 3, 4, 1, 2, 3, 4]]) 

 and the dimensions of the repeated tensor 3 are: 
 torch.Size([2, 12])


In [ ]:
# Repeat Interleave in Torch Tensors
# will be useful for Homework 4 Part 2 - Beam Search

original_tensor = torch.tensor([[1,2],[3,4]])
print("Tensor is \n", original_tensor, " with dimensions ", original_tensor.shape, "\n")

repeated_tensor1 = original_tensor.repeat_interleave(2)
print("Repeated tensor 1 is \n", repeated_tensor1, "\n\n", "and the dimensions of the repeated tensor 1 are: \n", repeated_tensor1.shape)

repeated_tensor2 = original_tensor.repeat_interleave(3, dim=0)
print("Repeated tensor 2 is \n", repeated_tensor2, "\n\n", "and the dimensions of the repeated tensor 2 are: \n", repeated_tensor2.shape)

repeated_tensor3 = original_tensor.repeat_interleave(3, dim=1)
print("Repeated tensor 3 is \n", repeated_tensor3, "\n\n", "and the dimensions of the repeated tensor 3 are: \n", repeated_tensor3.shape)


Tensor is 
 tensor([[1, 2],
        [3, 4]])  with dimensions  torch.Size([2, 2]) 

Repeated tensor 1 is 
 tensor([1, 1, 2, 2, 3, 3, 4, 4]) 

 and the dimensions of the repeated tensor 1 are: 
 torch.Size([8])
Repeated tensor 2 is 
 tensor([[1, 2],
        [1, 2],
        [1, 2],
        [3, 4],
        [3, 4],
        [3, 4]]) 

 and the dimensions of the repeated tensor 2 are: 
 torch.Size([6, 2])
Repeated tensor 3 is 
 tensor([[1, 1, 1, 2, 2, 2],
        [3, 3, 3, 4, 4, 4]]) 

 and the dimensions of the repeated tensor 3 are: 
 torch.Size([2, 6])


### 5d. Padding

Arrays/tensors need to be padded to ensure that computations can be optimized by transfroming the underlying data to become of the same size.

In [ ]:
# Padding Numpy Arrays

original_array = np.array([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])
print("Array is \n", original_array, " with dimensions ", original_array.shape, "\n")

# Setting the width of padding for each side
pad_left   = 1
pad_right  = 2
pad_top    = 1
pad_bottom = 2

padded_array1 = np.pad(original_array, pad_width =  ((pad_top, pad_bottom), (pad_left, pad_right)), mode = 'constant' )
print("Padded array 1 is \n", padded_array1, "\n\n", "and the dimensions of the padded array 1 are: \n", padded_array1.shape)

padded_array2 = np.pad(original_array, pad_width =  ((pad_top, pad_bottom), (pad_left, pad_right)), mode = 'edge' )
print("Padded array 2 is \n", padded_array2, "\n\n", "and the dimensions of the padded array 2 are: \n", padded_array2.shape)

padded_array3 = np.pad(original_array, pad_width =  ((pad_top, pad_bottom), (pad_left, pad_right)), mode = 'reflect' )
print("Padded array 3 is \n", padded_array3, "\n\n", "and the dimensions of the padded array 3 are: \n", padded_array3.shape)

padded_array4 = np.pad(original_array, pad_width =  ((pad_top, pad_bottom), (pad_left, pad_right)), mode = 'symmetric' )
print("Padded array 4 is \n", padded_array4, "\n\n", "and the dimensions of the padded array 4 are: \n", padded_array4.shape)

Array is 
 [[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]  with dimensions  (4, 4) 

Padded array 1 is 
 [[0 0 0 0 0 0 0]
 [0 1 2 3 4 0 0]
 [0 1 2 3 4 0 0]
 [0 1 2 3 4 0 0]
 [0 1 2 3 4 0 0]
 [0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0]] 

 and the dimensions of the padded array 1 are: 
 (7, 7)
Padded array 2 is 
 [[1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]
 [1 1 2 3 4 4 4]] 

 and the dimensions of the padded array 2 are: 
 (7, 7)
Padded array 3 is 
 [[2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]
 [2 1 2 3 4 3 2]] 

 and the dimensions of the padded array 3 are: 
 (7, 7)
Padded array 4 is 
 [[1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]
 [1 1 2 3 4 4 3]] 

 and the dimensions of the padded array 4 are: 
 (7, 7)


In [ ]:
# Padding Torch Tensors
# NOTE: Requires special package from torch.nn
from torch.nn import functional as F

original_tensor = torch.tensor([[1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4],
                 [1,2,3,4]])
print("Tensor is \n", original_tensor, " with dimensions ", original_tensor.shape, "\n")

# Setting the width of padding for each side
pad_left   = 1
pad_right  = 2
pad_top    = 1
pad_bottom = 2

padded_tensor1 = F.pad( original_tensor, (pad_left, pad_right, pad_top, pad_bottom), mode = 'constant' ) # ordering of padding widths is different
print("Padded tensor 1 is \n", padded_tensor1, "\n\n", "and the dimensions of the padded tensor 1 are: \n", padded_tensor1.shape)

Tensor is 
 tensor([[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]])  with dimensions  torch.Size([4, 4]) 

Padded tensor 1 is 
 tensor([[0, 0, 0, 0, 0, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 1, 2, 3, 4, 0, 0],
        [0, 0, 0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0, 0, 0]]) 

 and the dimensions of the padded tensor 1 are: 
 torch.Size([7, 7])


## **6. Mathematical Operations**


In this section we willcover  some of the most commonly used basic mathematical operations
1. Point-wise/element-wise operations
1. Redution operations
1. Comparison operations
1. Vector/Matrix operations

### 6a. Point-wise/Element-wise operations

In [ ]:
# Point-wise/element-wise Array operations

original_array1 = np.random.randint(3, size = (3,)) 
print("Original Array 1: \n", original_array1, " with dimensions ", original_array1.shape, "\n")

original_array2 = np.random.randint(3, size = (3,)) 
print("Original Array 2: \n", original_array2, " with dimensions ", original_array2.shape, "\n")

original_array3 = np.random.randint(3, size = (3, 4)) 
print("Original Array 3: \n", original_array3, " with dimensions ", original_array3.shape, "\n")

original_array4 = np.random.randint(3, size = (3, 4)) 
print("Original Array 4: \n", original_array4, " with dimensions ", original_array4.shape, "\n")

original_array5 = np.random.randint(3, size = (3, 1)) 
print("Original Array 5: \n", original_array5, " with dimensions ", original_array5.shape, "\n")



# Addition with Scalars
print("Original_Array1 + 10 =")
print(original_array1 + 10, "\n")

# Multiplication with Scalars:
print("Original_Array1 * -10 =")
print(original_array1 * -10, "\n")

# Elementwise Addition of Arrays
print("Original_Array1 + Original_Array2 =")
print(original_array1 + original_array2, "\n")

print("Original_Array3 + Original_Array4 =")
print(original_array3 + original_array4, "\n")

# Elementwise Multiplication of Arrays aka Hadmard Product
print("Original_Array1 * Original_Array2 =")
print(original_array1 * original_array2, "\n") # also equivalent to np.multiply(array1, array2)

print("Original_Array3 * Original_Array4 =")
print(original_array3 * original_array4, "\n") # also equivalent to np.multiply(array1, array2)

# Absolute value
print("abs (-10 * Original_Array1) =")
print(abs(-10*original_array1), "\n")

# Broadcasting b/w arrays of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the arrays should have length 1 in that specific dimension

print("Original_Array3 + Original_Array5 = \n")
print(original_array3 + original_array5)


Original Array 1: 
 [2 0 0]  with dimensions  (3,) 

Original Array 2: 
 [0 2 1]  with dimensions  (3,) 

Original Array 3: 
 [[0 0 0 0]
 [1 2 2 1]
 [0 1 1 1]]  with dimensions  (3, 4) 

Original Array 4: 
 [[1 1 1 2]
 [2 1 1 1]
 [2 0 0 0]]  with dimensions  (3, 4) 

Original Array 5: 
 [[1]
 [0]
 [1]]  with dimensions  (3, 1) 

Original_Array1 + 10 =
[12 10 10] 

Original_Array1 * -10 =
[-20   0   0] 

Original_Array1 + Original_Array2 =
[2 2 1] 

Original_Array3 + Original_Array4 =
[[1 1 1 2]
 [3 3 3 2]
 [2 1 1 1]] 

Original_Array1 * Original_Array2 =
[0 0 0] 

Original_Array3 * Original_Array4 =
[[0 0 0 0]
 [2 2 2 1]
 [0 0 0 0]] 

abs (-10 * Original_Array1) =
[20  0  0] 

Original_Array3 + Original_Array5 = 

[[1 1 1 1]
 [1 2 2 1]
 [1 2 2 2]]


In [ ]:
# Point-wise/element-wise Tensor operations

original_tensor1 = torch.rand(3)
print("Original Tensor 1: \n", original_tensor1, " with dimensions ", original_tensor1.shape, "\n")

original_tensor2 = torch.rand(3)
print("Original Tensor 2: \n", original_tensor1, " with dimensions ", original_tensor2.shape, "\n")

original_tensor3 = torch.rand(size=(3,4))
print("Original Tensor 3: \n", original_tensor1, " with dimensions ", original_tensor3.shape, "\n")

original_tensor4 = torch.rand(size=(3,4))
print("Original Tensor 4: \n", original_tensor1, " with dimensions ", original_tensor4.shape, "\n")

original_tensor5 = torch.rand(size=(3,1))
print("Original Tensor 5: \n", original_tensor5, " with dimensions ", original_tensor5.shape, "\n")

# Addition with Scalars
print("Original_Tensor1 + 10 = \n")
print(original_tensor1 + 10)

# Multiplication with Scalars:
print("Original_Tensor1 * -10 = \n")
print(original_tensor1 * -10)

# Elementwise Addition of Tensors
print("Original_Tensor1 + Original_Tensor2 =")
print(original_tensor1 + original_tensor2, "\n")

print("Original_Tensor3 + Original_Tensor4 =")
print(original_tensor3 + original_tensor4), "\n"

# Elementwise Multiplication of Tensors aka Hadmard Product
print("Original_Tensor1 * Original_Tensor2 =")
print(original_tensor1 * original_tensor2, "\n")

print("Original_Tensor3 * Original_Tensor4 =")
print(original_tensor3 * original_tensor4, "\n")

# Absolute value
print("abs (-10 * Original_Tensor1) =")
print(abs(-10*original_tensor1), "\n")

# Broadcasting b/w tensors of different dimensions
# Note: When broadting two multi-dimensional tensors, match their corresponding dimensions beginning from the last dimension.
# All dimensions should either match or one of the tensor should have length 1 in that specific dimension

print("Original_Tensor3 + Original_Tensor5 =")
print(original_tensor3 + original_tensor5, "\n")

Original Tensor 1: 
 tensor([0.8579, 0.8861, 0.9446])  with dimensions  torch.Size([3]) 

Original Tensor 2: 
 tensor([0.8579, 0.8861, 0.9446])  with dimensions  torch.Size([3]) 

Original Tensor 3: 
 tensor([0.8579, 0.8861, 0.9446])  with dimensions  torch.Size([3, 4]) 

Original Tensor 4: 
 tensor([0.8579, 0.8861, 0.9446])  with dimensions  torch.Size([3, 4]) 

Original Tensor 5: 
 tensor([[0.3178],
        [0.7811],
        [0.2159]])  with dimensions  torch.Size([3, 1]) 

Original_Tensor1 + 10 = 

tensor([10.8579, 10.8861, 10.9446])
Original_Tensor1 * -10 = 

tensor([-8.5792, -8.8606, -9.4459])
Original_Tensor1 + Original_Tensor2 =
tensor([1.2299, 1.6061, 1.8901]) 

Original_Tensor3 + Original_Tensor4 =
tensor([[1.5209, 1.4429, 0.9700, 1.6973],
        [1.1447, 1.2771, 0.8214, 1.3401],
        [0.9226, 0.3399, 1.0938, 1.7154]])
Original_Tensor1 * Original_Tensor2 =
tensor([0.3191, 0.6380, 0.8931]) 

Original_Tensor3 * Original_Tensor4 =
tensor([[0.5692, 0.4430, 0.1600, 0.7188],
   

### 6b. Reduction Operations

NumPy & Torch support all commonly used mathematical reduction operations such as sum(), mean(), std(), max(), argmax(), unique() etc. These can either be applied on the entire array/tensor or along specific dimensions.

In [ ]:
# Numpy Reduction Operations

original_array1 = np.random.randint(3, size = (3))
original_array2 = np.random.randint(3, size=(3,4))

print('Original array1: \n', original_array1)
print('Original array2: \n', original_array2)

print('Sum of array1 \n', original_array1.sum(), "\n\n")
print('Sum of array2 \n', original_array2.sum(), "\n\n")

print('Sum of array2 elements along axis 0 \n', original_array2.sum(axis=0), "\n\n")
print('Sum of array2 elements along axis 1 \n', original_array2.sum(axis=1), "\n\n")

Original array1: 
 [0 2 2]
Original array2: 
 [[1 0 0 0]
 [0 0 2 1]
 [0 2 0 2]]
Sum of array1 
 4 


Sum of array2 
 8 


Sum of array2 elements along axis 0 
 [1 2 2 3] 


Sum of array2 elements along axis 1 
 [1 3 4] 




In [ ]:
# Torch Reduction Operations

t1 = torch.rand(3)
t2 = torch.rand(size=(3,4))

original_tensor1 = np.random.randint(3, size = (3))
original_tensor2 = np.random.randint(3, size=(3,4))

print('Original tensor1: \n', original_tensor1)
print('Original tensor2: \n', original_tensor2)

print('Sum of tensor1 \n', original_tensor1.sum(), "\n\n")
print('Sum of tensor2 \n', original_tensor2.sum(), "\n\n")

print('Sum of tensor2 elements along axis 0 \n', original_tensor2.sum(axis=0), "\n\n")
print('Sum of tensor2 elements along axis 1 \n', original_tensor2.sum(axis=1), "\n\n")

Original tensor1: 
 [1 0 0]
Original tensor2: 
 [[2 1 2 2]
 [1 0 0 2]
 [1 1 0 0]]
Sum of tensor1 
 1 


Sum of tensor2 
 12 


Sum of tensor2 elements along axis 0 
 [4 2 2 4] 


Sum of tensor2 elements along axis 1 
 [7 3 2] 




### 6c. Comparison Operations

Comparison Operations preform comparision on the array/tensors as a whole as well as along particular axes.

In [ ]:
# Numpy Comparison Operations

original_array1 = np.random.randint(3, size=(3,4))
original_array2 = np.random.randint(3, size=(3,4))
original_array3 = np.random.randint(3, size=(3,4))

print('Original array1: \n', original_array1)
print('Original array2: \n', original_array2)
print('Original array2: \n', original_array3, "\n")

# Element-wise Comparison Operations
print('original_array1 > original_array2')
print(original_array1 > original_array2, "\n")

print('original_array2 != t3')
print(original_array2 != original_array3, "\n")

# Combining reduction operations with boolean tensors
print((original_array1 > original_array2).any(), "\n")
print((original_array1 > original_array2).all(), "\n")
print((original_array1 > original_array2).any(axis=0), "\n")
print((original_array1 > original_array2).any(axis=1), "\n")
print((original_array2 != original_array3).any(), "\n")
print((original_array2 != original_array3).all(), "\n")

Original array1: 
 [[0 1 0 1]
 [1 2 0 2]
 [0 0 0 2]]
Original array2: 
 [[1 2 2 0]
 [1 1 1 1]
 [0 1 0 0]]
Original array2: 
 [[1 2 0 2]
 [0 1 1 2]
 [0 1 1 1]] 

original_array1 > original_array2
[[False False False  True]
 [False  True False  True]
 [False False False  True]] 

original_array2 != t3
[[False False  True  True]
 [ True False False  True]
 [False False  True  True]] 

True 

False 

[False  True False  True] 

[ True  True  True] 

True 

False 



In [ ]:
# Torch Comparison Operations

original_tensor1 = torch.rand(size=(3,4))
original_tensor2 = torch.rand(size=(3,4))
original_tensor3 = torch.rand(size=(3,4))

print('Original tensor1: \n', original_tensor1)
print('Original tensor2: \n', original_tensor2)
print('Original tensor3: \n', original_tensor3, "\n")

# Element-wise Comparison Operations
print('original_tensor1 > original_tensor2')
print(original_tensor1 > original_tensor2, "\n")

print('original_tensor2 != t3')
print(original_tensor2 != original_tensor3, "\n\n")

# Combining reduction operations with boolean tensors
print((original_tensor1 > original_tensor2).any(), "\n")
print((original_tensor1 > original_tensor2).all(), "\n")
print((original_tensor1 > original_tensor2).any(axis=0), "\n")
print((original_tensor1 > original_tensor2).any(axis=1), "\n")
print((original_tensor2 != original_tensor3).any(), "\n")
print((original_tensor2 != original_tensor3).all(), "\n")

Original tensor1: 
 tensor([[0.6079, 0.1074, 0.6594, 0.7684],
        [0.5697, 0.1655, 0.1123, 0.3457],
        [0.7195, 0.9932, 0.7875, 0.4437]])
Original tensor2: 
 tensor([[0.6753, 0.0095, 0.0729, 0.7333],
        [0.2168, 0.7405, 0.1470, 0.2523],
        [0.0882, 0.7609, 0.4491, 0.8848]])
Original tensor3: 
 tensor([[0.8094, 0.7767, 0.5161, 0.3454],
        [0.3913, 0.5665, 0.7479, 0.1497],
        [0.9196, 0.4456, 0.0810, 0.2295]]) 

original_tensor1 > original_tensor2
tensor([[False,  True,  True,  True],
        [ True, False, False,  True],
        [ True,  True,  True, False]]) 

original_tensor2 != t3
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]]) 


tensor(True) 

tensor(False) 

tensor([True, True, True, True]) 

tensor([True, True, True]) 

tensor(True) 

tensor(True) 



### 6d. Vector/Matrix Operations

In this section we will cover some basic matrix and vector operations which will be useful for assignment.

Here is an example of matrix array multiplication between a $3 \times 1$ matrix array and a $1 \times 3$ matrix array:
$$
\boldsymbol{u} \boldsymbol{v}^T=
\left(\begin{array}{cc} 
u_1 \\
u_2 \\
u_3
\end{array}\right)
\left(\begin{array}{cc} 
v_1 & v_2 & v_3
\end{array}\right)
=
\left(\begin{array}{cc} 
u_1v_1 & u_1v_2 & u_1v_3\\
u_2v_1 & u_2v_2 & u_2v_3\\
u_3v_1 & u_3v_2 & u_3v_3
\end{array}\right)
$$ 

In [ ]:
# Numpy Vector/Matrix operations

# Vector x Vector
array1 = np.random.randn(3)
array2 = np.random.randn(3)

print('Array1 \n', array1)
print('Array2 \n', array2)

print('Matmul of the two arrays can be derived by using np.matmul(array1, array2) \n', np.matmul(array1, array2))
print("Matmul of the two arrays can also be derived by using array1@array2 \n", array1@array2)
print('Dimensions of resulting product: \n', np.matmul(array1, array2).shape)

# Matrix x Vector
array3 = np.random.randn(3, 4)
array4 = np.random.randn(4)

print('Array3 \n', array3, "\n")
print('Array4 \n', array4, "\n")

print('Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) \n', np.matmul(array3, array4))
print('Matmul of a vector and a matrix can also be derived by using array3@array4 \n', array3@array4)
print('Dimensions of resulting product: \n', np.matmul(array3, array4).shape)

# Matrix x Matrix 

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1', matrix1, "\n")
print('Matrix2', matrix2, "\n")

print('Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) \n', np.matmul(matrix1, matrix2))
print('Dimensions of resulting product: \n', np.matmul(matrix1, matrix2).shape, "\n")

Array1 
 [ 0.92525075 -0.90478616  1.84369153]
Array2 
 [ 1.52550724 -1.44553558  0.37716061]
Matmul of the two arrays can be derived by using np.matmul(array1, array2) 
 3.414745128921027
Matmul of the two arrays can also be derived by using array1@array2 
 3.414745128921027
Dimensions of resulting product: 
 ()
Array3 
 [[-0.07055723  0.60415971  0.472149    0.81991729]
 [ 0.90751962 -0.58582287  0.93755884 -0.25460809]
 [ 0.97359871  0.20728277  1.09964197  0.93989698]] 

Array4 
 [ 6.06389001e-01  1.76084071e-03 -9.90160143e-01  1.87239408e+00] 

Matmul of a vector and a matrix can be derived by using np.matmul(array3, array4) 
 [ 1.02598387 -0.85578171  1.26178043]
Matmul of a vector and a matrix can also be derived by using array3@array4 
 [ 1.02598387 -0.85578171  1.26178043]
Dimensions of resulting product: 
 (3,)
Matrix1 [[3 3 1]
 [2 1 3]] 

Matrix2 [[1 3]
 [0 0]
 [3 1]] 

Matmul of two matrices can be derived by using np.matmul(matrix1, matrix2) 
 [[ 6 10]
 [11  9]]
Dimension

In [ ]:
# Torch Vector/Matrix operations

# Vector x Vector
tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1', tensor1, "\n")
print('Tensor2', tensor2, "\n")

print('Matmul of the two tensors can be derived by using torch.matmul(tensor1, tensor2) \n', torch.matmul(tensor1, tensor2))
print('Dimensions of resulting product: \n', torch.matmul(tensor1, tensor2).shape, "\n")

# Matrix x Vector
tensor3 = torch.randn(3, 4)
tensor4 = torch.randn(4)

print('Tensor3', tensor3, "\n")
print('Tensor4', tensor4, "\n")

print('Matmul of the a vector and a matrix can be derived by using torch.matmul(tensor3, tensor4) \n', torch.matmul(tensor3, tensor4))
print('Dimensions of resulting product: \n', torch.matmul(tensor3, tensor4).shape, "\n")

# Matrix x Matrix
matrix1 = torch.randn(2, 3)
matrix2 = torch.randn(3, 2)

print('Matrix1', matrix1, "\n")
print('Matrix2', matrix2, "\n")

print('Matmul of two matrices can be derived by using torch.matmul(matrix1, matrix2) \n', torch.matmul(matrix1, matrix2))
print('Dimensions of resulting product: \n', torch.matmul(matrix1, matrix2).shape, "\n")


Tensor1 tensor([2.8880, 1.8429, 0.9809]) 

Tensor2 tensor([-0.3797, -1.6273,  0.5248]) 

Matmul of the two tensors can be derived by using torch.matmul(tensor1, tensor2) 
 tensor(-3.5808)
Dimensions of resulting product: 
 torch.Size([]) 

Tensor3 tensor([[ 0.5726,  0.6149, -0.9225, -0.4292],
        [-0.0803, -1.1858, -1.5992, -0.7179],
        [-1.8873,  2.1141, -1.0237, -0.8127]]) 

Tensor4 tensor([-1.0407,  1.4890,  0.4576, -0.2535]) 

Matmul of the a vector and a matrix can be derived by using torch.matmul(tensor3, tensor4) 
 tensor([ 0.0065, -2.2319,  4.8496])
Dimensions of resulting product: 
 torch.Size([3]) 

Matrix1 tensor([[-0.9865,  0.5242, -0.4363],
        [-0.0399, -1.2045,  0.0616]]) 

Matrix2 tensor([[ 0.5556, -0.3703],
        [-0.1451, -0.7339],
        [-1.0027,  1.2256]]) 

Matmul of two matrices can be derived by using torch.matmul(matrix1, matrix2) 
 tensor([[-0.1867, -0.5542],
        [ 0.0908,  0.9742]])
Dimensions of resulting product: 
 torch.Size([2, 2]) 



**Dot Product:** aka Inner product (Matrix multiplication relies on dot product to multiply various combinations of rows and columns.)

**Tensor Product:** Tensordot (also known as tensor contraction) sums the product of elements from a and b over the indices specified by a_axes and b_axes. The lists a_axes and b_axes specify those pairs of axes along which to contract the tensors.

To understand in depth please checkout: https://stackoverflow.com/questions/41870228/understanding-tensordot

**Einsum:** Imagine that we have two multi-dimensional arrays, A and B. Now let's suppose we want to... multiply A with B in a particular way to create new array of products; and then maybe sum this new array along particular axes; and then maybe transpose the axes of the new array in a particular order.
There's a good chance that einsum will help us do this faster and more memory-efficiently that combinations of the NumPy functions like multiply, sum and transpose will allow.

To understand in depth please checkout: https://stackoverflow.com/questions/26089893/understanding-numpys-einsum

In [ ]:
# Some More Numpy Vector/Matrix operations

matrix1 = np.random.randint(4, size = (2, 3))
matrix2 = np.random.randint(4, size = (3, 2))

print('Matrix1', matrix1, "\n")
print('Matrix2', matrix2, "\n")

# Dot Product
product = matrix1.dot(matrix2)

print('Using DOT: product= \n\n', product, '\n\nproduct.shape =', product.shape)
print("array3@array4 is an equivalent way of dot product \n", matrix1@matrix2, '\n\nproduct.shape =', (matrix1@matrix2).shape)

# Tensor Dot
array5 = np.random.randint(9, size=(3))
array6 = np.random.randint(9, size=(4,4))

print('Array5 \n', array5, "\n")
print('Array6 \n', array6, "\n")

product = np.tensordot(array5, array6, axes=0)

print('Using TENSORDOT: product = A⨂B =\n', product, '\n\nproduct.shape =', product.shape)

# Using einsum

product = np.einsum('ik, kj', matrix1, matrix2)
print('\n\nUsing einsum: product= \n\n', product, '\n\nproduct.shape =', product.shape)

    # Note, the above einsum notation is equivalent to the following
product = np.einsum('ik, kj -> ij', matrix1, matrix2)

Matrix1 [[0 2 0]
 [0 3 3]] 

Matrix2 [[3 0]
 [0 3]
 [1 3]] 

Using DOT: product= 

 [[ 0  6]
 [ 3 18]] 

product.shape = (2, 2)
array3@array4 is an equivalent way of dot product 
 [[ 0  6]
 [ 3 18]] 

product.shape = (2, 2)
Array5 
 [7 0 3] 

Array6 
 [[8 7 7 1]
 [8 4 7 0]
 [4 0 6 4]
 [2 4 6 3]] 

Using TENSORDOT: product = A⨂B =
 [[[56 49 49  7]
  [56 28 49  0]
  [28  0 42 28]
  [14 28 42 21]]

 [[ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]
  [ 0  0  0  0]]

 [[24 21 21  3]
  [24 12 21  0]
  [12  0 18 12]
  [ 6 12 18  9]]] 

product.shape = (3, 4, 4)


Using einsum: product= 

 [[ 0  6]
 [ 3 18]] 

product.shape = (2, 2)


In [ ]:
# Some More Torch Vector/Matrix operations

# Dot Product -- only takes in 1D vectors

tensor1 = torch.randn(3)
tensor2 = torch.randn(3)

print('Tensor1', tensor1, "\n")
print('Tensor2', tensor2, "\n")

product = torch.dot(tensor1, tensor2)

print('Using DOT: product= \n\n', product, '\n\nproduct.shape =', product.shape)

# Tensor Dot

tensor3 = torch.randn(3)
tensor4 = torch.randn(3,4)

print('tensor3 \n', array5, "\n")
print('tensor4 \n', array6, "\n")

product = torch.tensordot(tensor3, tensor4, dims=0)

print('Using TENSORDOT: product = A⨂B =\n', product, '\n\nproduct.shape =', product.shape)

# Einsum

matrix1 = torch.randn(2, 3)
matrix2 = torch.randn(3, 2)

print('Matrix1', matrix1, "\n")
print('Matrix2', matrix2, "\n")

product = torch.einsum('ik, kj', matrix1, matrix2)
print('\n\nUsing einsum: product= \n\n', product, '\n\nproduct.shape =', product.shape)

    # Note, the above einsum notation is equivalent to the following
product = torch.einsum('ik, kj -> ij', matrix1, matrix2)

Tensor1 tensor([-0.8864, -0.2119, -2.5407]) 

Tensor2 tensor([0.4786, 0.9196, 2.3265]) 

Using DOT: product= 

 tensor(-6.5299) 

product.shape = torch.Size([])
tensor3 
 [7 0 3] 

tensor4 
 [[8 7 7 1]
 [8 4 7 0]
 [4 0 6 4]
 [2 4 6 3]] 

Using TENSORDOT: product = A⨂B =
 tensor([[[ 0.2574,  0.3551,  0.1769,  0.2358],
         [-0.0885, -0.5970,  0.0283,  0.2319],
         [-0.1933, -0.2503,  0.0059,  0.1332]],

        [[ 0.6940,  0.9575,  0.4769,  0.6359],
         [-0.2387, -1.6096,  0.0763,  0.6252],
         [-0.5212, -0.6749,  0.0158,  0.3592]],

        [[ 0.1577,  0.2176,  0.1084,  0.1445],
         [-0.0542, -0.3657,  0.0173,  0.1421],
         [-0.1184, -0.1533,  0.0036,  0.0816]]]) 

product.shape = torch.Size([3, 3, 4])
Matrix1 tensor([[-0.6703, -0.8116,  0.8578],
        [-2.1923, -0.4673, -0.9846]]) 

Matrix2 tensor([[-0.0349, -0.0076],
        [ 0.2696, -0.2484],
        [-0.7032, -0.7199]]) 



Using einsum: product= 

 tensor([[-0.7986, -0.4108],
        [ 0.6428,  0.84